repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: black
          name: black
          entry: poetry run black evm_sc_utils/
          language: system
          always_run: true
          pass_filenames: false
        - id: pylint
          name: pylint
          entry: poetry run pylint evm_sc_utils/
          language: system
          always_run: true
          pass_filenames: false
        - id: mypy
          name: mypy
          entry: poetry run mypy evm_sc_utils/
          language: system
          always_run: true
          pass_filenames: false